---
- name: Reboot cluster servers staggered
  hosts: server
  gather_facts: true
  become: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        test_command: kubectl get nodes

- name: Reboot cluster agents staggered
  hosts: agent
  gather_facts: true
  become: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
