---
base_os_packages:
  - curl
  - ca-certificates
  - apt-transport-https
  - software-properties-common
  - socat
  - conntrack
  - iptables
  - nfs-common
  - ebtables
  - ethtool
  - unzip
  - python3
  - python3-pip

base_os_sysctl_params:
  net.ipv4.ip_forward: 1
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv6.conf.all.disable_ipv6: 0
  fs.inotify.max_user_instances: 512
  fs.inotify.max_user_watches: 524288
