all:
  vars:
    ansible_user: "{{ k3s_sudo_user }}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_password: "{{ k3s_sudo_password }}"
    # set node 1
    k3s_api_endpoint: 192.168.10.254
  children:
    control_plane:
      hosts:
        pi-cluster-1.local:
          k3s_static_ipv4: 192.168.10.254/24
        pi-cluster-2.local:
          k3s_static_ipv4: 192.168.10.253/24
        pi-cluster-3.local:
          k3s_static_ipv4: 192.168.10.252/24
    workers:
      hosts:
        pi-cluster-4.local:
          k3s_static_ipv4: 192.168.10.251/24
    k3s_cluster:
      children:
        control_plane:
        workers:
