---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_port: 22
    ansible_user: "{{ sudo_user }}"
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_password: "{{ sudo_password }}"
static_network_configuration:
  children:
    nodes:
      hosts:
        # dns-internal-1.local:
        #   static_ipv4: "{{ (nodes['dns-node-1'] }}"
        pi-cluster-1.local:
          static_ipv4: "{{ nodes['cluster-node-1'] }}"
        pi-cluster-2.local:
          static_ipv4: "{{ nodes['cluster-node-2'] }}"
        pi-cluster-3.local:
          static_ipv4: "{{ nodes['cluster-node-3'] }}"
        pi-cluster-4.local:
          static_ipv4: "{{ nodes['cluster-node-4'] }}"
k3s_cluster:
  children:
    server:
      hosts:
        "{{ (nodes['cluster-node-1'] | split('/'))[0] }}": {}
        "{{ (nodes['cluster-node-2'] | split('/'))[0] }}": {}
        "{{ (nodes['cluster-node-3'] | split('/'))[0] }}": {}
    agent:
      hosts:
        "{{ (nodes['cluster-node-4'] | split('/'))[0] }}": {}
  # Required Vars
  vars:
    k3s_version: v1.34.1+k3s1
    token: "{{ k3s_cluster_token }}"   
    # after DNS lands,
    # change this value to host name of the leader node
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

    # Optional vars
    # extra_server_args: ""
    # extra_agent_args: ""
    # extra_install_envs: { 'INSTALL_K3S_SKIP_SELINUX_RPM': 'true' }
    # cluster_context: k3s-ansible
    # api_port: 6443
    # k3s_server_location: /var/lib/rancher/k3s
    # systemd_dir: /etc/systemd/system
    # extra_service_envs: [ 'ENV_VAR1=VALUE1', 'ENV_VAR2=VALUE2' ]
    # user_kubectl: true, by default kubectl is symlinked and configured for use by ansible_user. Set to false to only kubectl via root user.

    # Manifests or Airgap should be either full paths or relative to the playbook directory.
    # List of locally available manifests to apply to the cluster, useful for PVCs or Traefik modifications.
    # extra_manifests: [ '/path/to/manifest1.yaml', '/path/to/manifest2.yaml' ]
    # airgap_dir: /tmp/k3s-airgap-images

    # server_config_yaml:  |
    #   This is now an inner yaml file. Maintain the indentation.
    #   YAML here will be placed as the content of /etc/rancher/k3s/config.yaml
    #   See https://docs.k3s.io/installation/configuration#configuration-file
    # agent_config_yaml:  |
    #   Same as server_config_yaml, but for the agent nodes.
    #   YAML here will be placed as the content of /etc/rancher/k3s/config.yaml
    #   See https://docs.k3s.io/installation/configuration#configuration-file
    # registries_config_yaml:  |
    #   Containerd can be configured to connect to private registries and use them to pull images as needed by the kubelet.
    #   YAML here will be placed as the content of /etc/rancher/k3s/registries.yaml
    #   See https://docs.k3s.io/installation/private-registry

