---
k3s_cluster:
  children:
    server:
      hosts:
        pi-cluster-1.local:
          ansible_host: 192.168.10.253
          k3s_static_ipv4: 192.168.10.253/24
        pi-cluster-2.local:
          ansible_host: 192.168.10.252
          k3s_static_ipv4: 192.168.10.252/24
        pi-cluster-3.local:
          ansible_host: 192.168.10.251
          k3s_static_ipv4: 192.168.10.251/24
    agent:
      hosts:
        pi-cluster-4.local:
          ansible_host: 192.168.10.250
          k3s_static_ipv4: 192.168.10.250/24
  vars:
    ansible_user: "{{ lookup('env', 'K3S_SSH_USER') | default(k3s_sudo_user, true) }}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_password: "{{ k3s_sudo_password }}"
    k3s_version: v1.29.15+k3s1
    token: "{{ vault_k3s_cluster_token }}"
    api_endpoint: 192.168.10.253

control_plane:
  children:
    server:

workers:
  children:
    agent:
