all:
  vars:
    ansible_user: "{{ k3s_sudo_user }}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_password: "{{ k3s_sudo_password }}"
  children:
    control_plane:
      hosts:
        pi-cluster-1.local:
        pi-cluster-2.local:
        pi-cluster-3.local:
    workers:
      hosts:
        pi-cluster-4.local:
    k3s_cluster:
      children:
        control_plane:
        workers:
